# docker-compose.yml
version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - oauth
    environment:
      - RABBITMQ_HOST=rabbitmq
      - OAUTH_HOST=oauth

  rabbitmq:
    build: rabbitmq
    ports:
      - "5672:5672"

  oauth:
    build: oauth
    ports:
      - "8081:8081"
